image: circleci/node:8.12.0-browsers

pipelines:
  default:
    - step:
        caches:
          - node
        script: 
          - yarn install
          - yarn run lint
          - xvfb-run -a --server-args="-screen 0 1024x768x24" yarn run test